services:
  core-api:
    build:
      context: ./core-api
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./core-api
        target: /app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000